services:
  home-health-site-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: health-site-cft
    restart: always
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - tunnel-network

  home-health-site:
    image: ghcr.io/kengbailey/home-health-site:main
    restart: unless-stopped
    container_name: home-health-site
    depends_on:
      - home-health-site-cloudflared
    volumes:
      - ./data:/app/data
    networks:
      - tunnel-network

networks:
  tunnel-network:
    driver: bridge
